name: Check License

on:
  pull_request:
    paths:
    - 'utils/**/requirements.txt'
    - 'attestation/**/requirements.txt'
    - 'tests/**/requirements.txt'
  workflow_dispatch:

jobs:
  codescan:
    #runs-on: self-hosted
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Check License
        run: |
          set -ex
          python3 -m pip list
          python3 -m pip install liccheck
          python3 -m pip install --upgrade pip
          python3 -m pip list
          for f in $(find -type f -name "requirements.txt"); do
            cat $f | while read pymodule; do
              python3 -m pip install $pymodule
            done
            liccheck -s .github/.license_check.ini -r $f
          done
